services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8888:8888"
    env_file:
      - backend/.env
    command: sh -c "npm run setup && npm run dev"
    networks:
      - server-mongo
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - server-mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - server-mongo
    environment:
      - MONGO_INITDB_DATABASE=local-idurar-erp-crp

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-remote-write-receiver
    networks:
      - server-mongo

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3003:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - server-mongo

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  server-mongo: