services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8888:8888"
    env_file:
      - backend/.env
    command: sh -c "npm run setup && npm run dev"
    networks:
      - server-mongo
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    networks:
      - server-mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - server-mongo
    environment:
      - MONGO_INITDB_DATABASE=local-idurar-erp-crp

volumes:
  mongodb_data:

networks:
  server-mongo: